local nnoremap = require("user.keymap").nnoremap

nnoremap("<leader>m", function()
	require("harpoon.mark").add_file()
end, { desc = "Harpoon add to quick access", silent = true })
nnoremap("<leader>h", function()
	require("harpoon.ui").toggle_quick_menu()
end, { desc = "Harpoon list marked files", silent = true })

-- easy switching within first 10 files
nnoremap("<leader>1", function()
	require("harpoon.ui").nav_file(1)
end, { desc = "Harpoon open marked file 1", silent = true })
nnoremap("<leader>2", function()
	require("harpoon.ui").nav_file(2)
end, { desc = "Harpoon open marked file 2", silent = true })
nnoremap("<leader>3", function()
	require("harpoon.ui").nav_file(3)
end, { desc = "Harpoon open marked file 3", silent = true })
nnoremap("<leader>4", function()
	require("harpoon.ui").nav_file(4)
end, { desc = "Harpoon open marked file 4", silent = true })
nnoremap("<leader>5", function()
	require("harpoon.ui").nav_file(5)
end, { desc = "Harpoon open marked file 5", silent = true })
nnoremap("<leader>6", function()
	require("harpoon.ui").nav_file(6)
end, { desc = "Harpoon open marked file 6", silent = true })
nnoremap("<leader>7", function()
	require("harpoon.ui").nav_file(7)
end, { desc = "Harpoon open marked file 7", silent = true })
nnoremap("<leader>8", function()
	require("harpoon.ui").nav_file(8)
end, { desc = "Harpoon open marked file 8", silent = true })
nnoremap("<leader>9", function()
	require("harpoon.ui").nav_file(9)
end, { desc = "Harpoon open marked file 9", silent = true })
nnoremap("<leader>0", function()
	require("harpoon.ui").nav_file(10)
end, { desc = "Harpoon open marked file 10", silent = true })
