local remap = require("user.keymap")
local nnoremap = remap.nnoremap
local telescope = require("telescope.builtin")

nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>ps", function()
	telescope.grep_string({ search = vim.fn.input("Grep For > ") })
end)
nnoremap("<C-g>", function()
	telescope.git_files()
end)
nnoremap("<leader>pf", function()
	telescope.find_files()
end)
nnoremap("<leader>pb", function()
	telescope.buffers()
end)
nnoremap("<leader>vh", function()
	telescope.help_tags()
end)
nnoremap("<leader>ld", function()
	telescope.lsp_document_symbols()
end)
nnoremap("<leader>lw", function()
	telescope.lsp_workspace_symbols()
end)
nnoremap("<leader>li", function()
	telescope.lsp_implementations()
end)
--[[
nnoremap("<leader>lr", function()
	telescope.lsp_references()
end)
--]]
