local remap = require("user.keymap")
local nnoremap = remap.nnoremap

nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>ps", function()
	require("telescope.builtin").grep_string({ search = vim.fn.input("Grep For > ") })
end)
nnoremap("<C-g>", function()
	require("telescope.builtin").git_files()
end)
nnoremap("<leader>pf", function()
	require("telescope.builtin").find_files()
end)
nnoremap("<leader>pb", function()
	require("telescope.builtin").buffers()
end)
nnoremap("<leader>vh", function()
	require("telescope.builtin").help_tags()
end)
nnoremap("<leader>ld", function()
	require("telescope.builtin").lsp_document_symbols()
end)
nnoremap("<leader>lw", function()
	require("telescope.builtin").lsp_workspace_symbols()
end)
