local remap = require("user.keymap")
local nnoremap = remap.nnoremap
local telescope = require("telescope.builtin")

nnoremap("<C-p>", ":Telescope ")
nnoremap("<leader>s", function()
	telescope.grep_string({ search = vim.fn.input("Grep for: ") })
end)
nnoremap("<leader>q", function()
	telescope.git_files()
end)
nnoremap("<leader>f", function()
	telescope.find_files()
end)
nnoremap("<leader>b", function()
	telescope.buffers()
end)
nnoremap("<leader>vh", function()
	telescope.help_tags()
end)
nnoremap("<leader>ld", function()
	telescope.lsp_document_symbols()
end)
nnoremap("<leader>lw", function()
	telescope.lsp_workspace_symbols()
end)
nnoremap("<leader>li", function()
	telescope.lsp_implementations()
end)
nnoremap("<leader>rr", function()
	telescope.lsp_references()
end)
nnoremap("<leader>td", function()
	telescope.diagnostics()
end)
